name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run unit tests with coverage
      run: |
        pip install coverage
        coverage run -m unittest discover -s . -p "test_*.py"
        coverage xml

    - name: Upload coverage to GitHub
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Ensure the train_model.yaml file is present
      run: test -f train_model.yaml